### ISSUE TITLE
Option to disallow TXT submissions

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#101]
**Is your feature request related to a problem? Please describe.**
At WMT22, we run into issues as the pipeline downstream of processing submissions is not well prepared for TXT submissions. Would be great to have an option to forbid everything except XML, or integrate a converter that exports all submissions from OCELoT in the same format.

**Comment by cfedermann** [comment]
We can phase out non-XML format usage for WMT23/OCELoT 1.0.

Adding conversion tools would be a nice feature as well.

**Comment by cfedermann** [comment]
It may be easiest to specify, on the `Competition` level, which submission formats are valid. Then, it may be trivial to use the per-instance subset of submission formats for any of the forms.

This may require some additional checks preventing data from being submitted manually, though...

**Comment by cfedermann** [comment]
Not so easy, as the file format has to be specified during test set creation...

**Comment by cfedermann** [comment]
Commit https://github.com/AppraiseDev/OCELoT/commit/7074a9fce98f3e9703f901226f828bb59636c823 removes `TXT` and `SGML` from the set of possible file formats.

**Comment by cfedermann** [comment]
A more elegant way that does not break tests...

Commit https://github.com/AppraiseDev/OCELoT/commit/7c958e0fb6f098197e8c3b2ac8415edf3f74c2df ensures that the `SubmissionForm` widget for `file_format` is readonly. Inside `views.py` we set this to `XML`. Thus, it is only possible to upload XML files via the UI.

Testing and backend ops may still use `TXT` and `SGML`.

**Comment by cfedermann** [comment]
Done.
