### ISSUE TITLE
Set up default primary system to avoid missing participants

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#104]
**Is your feature request related to a problem? Please describe.**
When participant forgets to set up primary system, they are removed from evaluation

**Describe the solution you'd like**
One suggestion: Set the first submission as a primary.

**Comment by cfedermann** [comment]
By convention, I will make the last submission the default primary submission.

**Comment by cfedermann** [comment]
![image](https://github.com/AppraiseDev/OCELoT/assets/336872/928d76d7-19f9-4f5a-a09b-2c591b1a1ec3)

**Comment by cfedermann** [comment]
This allows the user to specify if a new submission should be designated as `is_primary` at submission time.

If the submission results in an invalid `-1` score, the field will not be set. Otherwise, `is_primary` will be set to `True`.

**Comment by cfedermann** [comment]
On a `Team` level, the default order will be defined as such:

1. highest-scoring, valid `Submission`; or 
2. the latest, valid `Submission`.

**Comment by cfedermann** [comment]
Note that this forces users to explicitly withdraw from a language pair/test set if they do not want to participate in that one!

**Comment by cfedermann** [comment]
This has been merged from `dev` into `main`, thus closing the issue.
