### ISSUE TITLE
Allow submitting before verifying teams

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#105]
**Is your feature request related to a problem? Please describe.**
non-verified teams must wait for verification before they can start submitting, which means they need to visit the page twice instead of doing it at once. 

**Describe the solution you'd like**
Allow submitting right after registration, but do not show the scores for teams that are not verified yet.
Problem: non-verified submissions must not see the scores to avoid hill-climbing on scores with multiple non-verified accounts

**Comment by cfedermann** [comment]
We decided not to do this.
