### ISSUE TITLE
Remve/rename abstract field from ocelot

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#107]
**Is your feature request related to a problem? Please describe.**
There is a field for abstract in Ocelot, that is confusing with Abstract paper we ask them to collect. This field could be removed or at least renamed to "description" to avoid confusion (last year one participant was removed due to this).
Is this field used? Maybe for short system description in findings paper?

**Comment by kocmitom** [comment]
Perhaps it is used for the short paragraph in the findings paper. But it shouldn't be named Abstract to avoid confusion

**Comment by cfedermann** [comment]
![image](https://github.com/AppraiseDev/OCELoT/assets/336872/187ef1f3-ea3d-4c28-81b4-e3666fd784fb)

Now labelled as "paragraph for the overview paper".

Closing this issue as it seems to be resolved. @kocmitom, please let me know if you disagree. Thank you!
