### ISSUE TITLE
Languages should be sorted alphabetically in the admin panel

### ISSUE THREAD

**Issue by snukky** [AppraiseDev/OCELoT#49]
**Describe the bug**
When creating new test sets in the admin panel, the select box with languages seems having them sorted by their IDs. This makes finding languages suboptimal and alphabetical sorting would be much more convinient.

**To Reproduce**
Start adding a new test set through the admin panel.

**Expected behavior**
Languages in the select box are sorted alphabetically by their names.

**Comment by cfedermann** [comment]
Fixed in 4aa33baa336d09bf816213853a40a284005e36d1
