### ISSUE TITLE
Unverified team shouldn't be able to submit

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#56]
The interface seems like an unverified team can submit translations, however, it blocks the submission. Maybe they shouldn't see the page at all until their verification.

**Comment by cfedermann** [comment]
Addressed in https://github.com/AppraiseDev/OCELoT/commit/0e2e44e228754d0e7646ced19e0fc1b592d7a029

**Comment by cfedermann** [comment]
Team verification status will now also be shown as `#verifiedteam` or `#unverifiedteam` in the #tags footer.

**Comment by cfedermann** [comment]
![image](https://github.com/AppraiseDev/OCELoT/assets/336872/5221033e-9f8b-411c-ba71-71b9c27348d3)

This closes the issue.
