### ISSUE TITLE
Validation error when score -1

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#58]
As fixed with https://github.com/AppraiseDev/OCELoT/commit/0ac45f450ec177620d3765b0a0fbe7f5988923ba

We would need a proper validation error in case we end up in the -1 scenario

**Comment by cfedermann** [comment]
@kocmitom can you please remind me: when did this happen and where would you like to throw a `ValidationError`?

**Comment by kocmitom** [comment]
I do not remember the details, but the issue was that the last year we did a quick fix by making score -1 when it failed. And we should make a proper validation of that error.

**Comment by cfedermann** [comment]
Unclear what the desired change of behaviour here is... closing as wontfix.
