### ISSUE TITLE
Secondary/contrastive submissions

### ISSUE THREAD

**Issue by snukky** [AppraiseDev/OCELoT#62]
**Is your feature request related to a problem? Please describe.**
Some shared tasks would like to be able to collect not only primary submissions, but also secondary/contrastive ones.

**Describe the solution you'd like**
A team gets an option to select a secondary submission for each test set, similarly as it's now with primary submissions. An administrator can download a package with all primary and secondary submissions from the admin panel.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by cfedermann** [comment]
@snukky do we still need this? If so, for which shared tasks?

I can look into this if needed...

**Comment by cfedermann** [comment]
@kocmitom @snukky: what is our stance on secondary/contrastive submissions for WMT23?

**Comment by snukky** [comment]
There was a shared task that wanted this. IMO at this moment it's a good-to-have feature, not a must-have one

**Comment by cfedermann** [comment]
Fixed in `dev` branch.

**Comment by cfedermann** [comment]
This has been merged from `dev` into `main`, thus closing the issue.
