### ISSUE TITLE
Not being too restrictive about formatting

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#87]
**Describe the bug**
Since researchers are converting files by wrap.py, they can miss adding the filename extensions ".xml" which will render their submission invalid. 
https://github.com/AppraiseDev/OCELoT/blob/main/leaderboard/models.py#L240

What about removing that condition? Or alternatively extending the help (I will create PR).

**Comment by snukky** [comment]
Related to #24

**Comment by cfedermann** [comment]
We have three different file types.

Using a convention regarding their extensions is the only authoritative way to distinguish between formats.

People can simply name their files correctly. It takes a few seconds in case you forget to do so in the first place.
