### ISSUE TITLE
Difference between "active" and "verified" flag for teams

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#89]
Why is the "active" flag set to False for newly created teams? Shouldn't it be set to active? And what does it affect (in contrast to "verified")?

**Comment by cfedermann** [comment]
The semantic difference is that:

    a. `is_active` should control whether a team is active and can be used; while
    b. `is_verified` should control whether a team can submit.

At this time, both are NOT used to enforce the above-mentioned criteria.

We should clean this up.

**Comment by cfedermann** [comment]
Teams `is_verified` status will now correctly decide if they can submit or not.

**Comment by cfedermann** [comment]
There are no current plans to enforce a team's `is_active` status.
