### ISSUE TITLE
Allow sorting tables in the admin panel by a column

### ISSUE THREAD

**Issue by kocmitom** [AppraiseDev/OCELoT#96]
**Is your feature request related to a problem? Please describe.**
When searching in the admin, it would be useful to have an option to sort by a column.

**Comment by snukky** [comment]
It's enabled for some columns in some models, e.g. dates in Competition, file format and others in Submission. Which model/column would you like to add to it, @kocmitom?

**Comment by kocmitom** [comment]
I needed different things in the last week. For example sorting by submission name to get the last submission. Sorting submission by teams, because some teams are not possible to search for (ALMAnaCH - Inria).
Could it be allowed for all of them?

**Comment by cfedermann** [comment]
Implemented fix in https://github.com/AppraiseDev/OCELoT/commit/043863c37c31422d3a3313911b7eea7f14c4eb3c

**Comment by cfedermann** [comment]
Need to verify that this actually works as intended, then can be closed.

**Comment by cfedermann** [comment]
Done.
